---
GSMPM:
  RLC层上行EGPRS流量(Mbit): {}
  RLC层下行EGPRS流量(Mbit): {}
  RLC层上行GPRS流量(Mbit): {}
  RLC层下行GPRS流量(Mbit): {}
  PDCH复用度:
    范围规则: ! '[0,16]'
  低编码比例(%):
    范围规则: ! '[0,1]'
  中编码比例(%):
    范围规则: ! '[0,1]'
  高编码比例(%):
    范围规则: ! '[0,1]'
  下行TBF掉线率(%):
    范围规则: ! '[0,1]'
  下行TBF建立成功率(%):
    范围规则: ! '[0,1]'
  小区掉话率(%):
    范围规则: ! '[0,1]'
  话音信道掉话率(%):
    范围规则: ! '[0,1]'
  SDCCH拥塞率(%):
    范围规则: ! '[0,1]'
  TCH拥塞率（含切）(%):
    范围规则: ! '[0,1]'
  TCH拥塞率（不含切）(%):
    范围规则: ! '[0,1]'
  ! '*无线接通率(%)*':
    范围规则: ! '[0,1]'
  无线接入性:
    范围规则: ! '[0,1]'
  SDCCH话务量: {}
  SDCCH试呼次数: {}
  SDCCH占用次数:
    字段关联规则: <SDCCH试呼次数
  SDCCH溢出次数:
    字段关联规则: <SDCCH试呼次数
  SDCCH分配失败次数:
    字段关联规则: <SDCCH试呼次数
  SDCCH掉话次数:
    字段关联规则: <SDCCH试呼次数
  小区总话务量:
    字段关联规则: ==全速率话音信道话务量+半速率话音信道话务量
  全速率话音信道话务量:
    字段关联规则: <=小区总话务量
  半速率话音信道话务量:
    字段关联规则: <=小区总话务量
  AMR半速率话务量:
    字段关联规则: <=AMR小区总话务量
  AMR全速率话务量:
    字段关联规则: <=AMR小区总话务量
  AMR小区总话务量:
    字段关联规则: ==AMR全速率话务量+AMR半速率话务量
  TCH信道可用数: {}
  话音信道切换试呼次数: {}
  话音信道切换占用次数:
    字段关联规则: <话音信道切换占用次数
  话音信道试呼次数（不含切换）: {}
  话音信道溢出次数（不含切换）:
    字段关联规则: <话音信道试呼次数（不含切换）
  话音信道分配失败次数(不含切换):
    字段关联规则: <话音信道试呼次数（不含切换）
  话音信道占用次数(不含切换):
    字段关联规则: <话音信道试呼次数（不含切换）
  话音信道试呼次数（含切换）: {}
  话音信道溢出次数（含切换）:
    字段关联规则: <话音信道试呼次数（含切换）
  话音信道分配失败次数(含切换):
    字段关联规则: <话音信道试呼次数（含切换）
  话音信道占用次数(含切换):
    字段关联规则: <话音信道试呼次数（含切换）
  话音信道掉话次数:
    字段关联规则: 话音信道掉话次数<话音信道占用次数(含切换)
  占用的PDCH的平均数目: {}
  PDCH平均可用数: {}
  PDCH承载效率: {}
  PDCH分配请求次数: {}
  PDCH分配失败次数:
    字段关联规则: <PDCH分配请求次数
  上行TBF建立尝试次数: {}
  上行TBF成功建立次数:
    字段关联规则: <=上行TBF建立尝试次数
  下行TBF建立尝试次数: {}
  下行TBF成功建立次数:
    字段关联规则: <=下行TBF建立尝试次数
  上行TBF异常中断次数:
    字段关联规则: <=上行TBF建立尝试次数
  下行TBF异常中断次数:
    字段关联规则: <=下行TBF建立尝试次数
  下行平均并发TBF数: {}
  切换出成功率(汇总)(%):
    范围规则: ! '[0,1]'
  切换入成功率（汇总）(%):
    范围规则: ! '[0,1]'
  ! '*小区切出试呼次数(汇总)*': {}
  ! '*小区切入试呼次数(汇总)*': {}
  ! '*切出成功次数(汇总)*':
    字段关联规则: <=*切出成功次数（汇总）*
  ! '*切入成功次数(汇总)*':
    字段关联规则: <=*小区切入试呼次数（汇总）*
  干扰频带1: {}
  干扰频带2: {}
  干扰频带3: {}
  干扰频带4: {}
  干扰频带5: {}
  下行链路无线数据块重传数(EGPRS): {}
  下行RLC数据块个数(MCS1编码): {}
  下行RLC数据块个数(MCS2编码): {}
  下行RLC数据块个数(MCS3编码): {}
  下行RLC数据块个数(MCS4编码): {}
  下行RLC数据块个数(MCS5编码): {}
  下行RLC数据块个数(MCS6编码): {}
  下行RLC数据块个数(MCS7编码): {}
  下行RLC数据块个数(MCS8编码): {}
  下行RLC数据块个数(MCS9编码): {}
GSMRES:
  载频数量:
    范围规则: ! '[1,20]'
  TCH总数:
    范围规则: ! '[1,160]'
  PDCH静态信道配置数:
    范围规则: ! '[1,160]'
  SDCCH信道数:
    范围规则: ! '[1,160]'
  经度:
    范围规则: ! '[110.0,120.0]'
  纬度:
    范围规则: ! '[28.0,33.0]'
  BCCH频点:
    范围规则: ! '[1,94;512,636]'
  TCH频点: {}
  天线下倾角:
    范围规则: ! '[0,25]'
  方位角:
    范围规则: ! '[0,360]'
  覆盖场景:
    范围规则: ! '[1,41]'
  覆盖类型:
    范围规则: ! '{室外,室内}'
TDPM:
  RNC请求释放的电路域RAB数（小区级）: {}
  RNC请求释放电路域Iu连接对应的RAB数（小区级）: {}
  成功建立的电路域RAB数（小区级）: {}
  RRC连接请求次数: {}
  RRC连接建立成功次数: {}
  成功建立的电路域会话类窄带AMR RAB数: {}
  成功建立的电路域会话类12.2K RAB数: {}
  请求建立的电路域会话类窄带AMR RAB数: {}
  请求建立的电路域会话类12.2K RAB数: {}
  电路域系统间小区间切换出成功次数（TD,SCDMA->GSM）: {}
  原因为11的RRC连接建立成功次数: {}
EPAR:
  最小接入电平:
    范围规则: ! '[85,103]'
  下行不连续发射开关:
    范围规则: ! '{ON,OFF}'
  上行不连续发射开关:
    范围规则: ! '[1,2]'
  GAMMA功率值:
    范围规则: ! '[0,32]'
  小区重选偏置:
    范围规则: ! '[0,10]'
  QSearch_I:
    范围规则: ! '[0,15]'
  TDD_OFFSET:
    范围规则: ! '[0,15]'
  上行链路断开计算器:
    范围规则: ! '[0,32]'
  下行链路误码断开计数器:
    范围规则: ! '[0,32]'
  RLINKTAFR:
    范围规则: ! '[0,32]'
  RLINKTAHR:
    范围规则: ! '[0,32]'
  周期性位置更新定时器:
    范围规则: ! '[8,20]'
  多频段指示:
    范围规则: ! '[0,2]'
  1等级上行干扰门限值:
    范围规则: ! '[0,63]'
  2等级上行干扰门限值:
    范围规则: ! '[0,63]'
  3等级上行干扰门限值:
    范围规则: ! '[0,63]'
  4等级上行干扰门限值:
    范围规则: ! '[0,63]'
  最大重发次数:
    范围规则: ! '[2,4]'
NPAR: {}
HPAR:
  MS最小接收信号等级:
    范围规则: ! '[8,25]'
  全速率呼叫下行DTX:
    范围规则: ! '{YES,NO}'
  半速率呼叫下行DTX:
    范围规则: ! '{YES,NO}'
  下行功率控制允许:
    范围规则: ! '{YES,NO}'
  全速率呼叫上行DTX:
    范围规则: ! '{SHALL_USE,SHALL_NOT_USE}'
  半速率呼叫上行DTX:
    范围规则: ! '{SHALL_USE,SHALL_NOT_USE}'
  上行功率控制允许:
    范围规则: ! '{YES,NO}'
  小区重选偏移:
    范围规则: ! '[0,8]'
  切换候选小区最小下行功率:
    范围规则: ! '[10,25]'
  QSearch_I:
    范围规则: ! '[7,8]'
  TDD_OFFSET:
    范围规则: ! '[5,8]'
  无线链路失效计数器:
    范围规则: ! '[0,32]'
  T200SDCCH:
    范围规则: ! '[0,125]'
  T200SACCHSDCCH:
    范围规则: ! '[0,250]'
  T200SDCCHSAPI3:
    范围规则: ! '[0,125]'
  T200FACCH/全速率:
    范围规则: ! '[0,86]'
  T200FACCH/半速率:
    范围规则: ! '[0,100]'
  T200SACCHTCHSAPI0:
    范围规则: ! '[0,250]'
  T200SACCHTCHSAPI3:
    范围规则: ! '[0,250]'
  SACCH复帧数[SACCH周期]:
    范围规则: ! '[0,32]'
  AFRSACCH复帧数:
    范围规则: ! '[0,32]'
  AHRSACCH复帧数:
    范围规则: ! '[0,32]'
  AFR无线链路失效计数器:
    范围规则: ! '[0,32]'
  AHR无线链路失效计数器:
    范围规则: ! '[0,32]'
  干扰带门限0:
    范围规则: ! '[48,110]'
  干扰带门限1:
    范围规则: ! '[48,110]'
  干扰带门限2:
    范围规则: ! '[48,110]'
  干扰带门限3:
    范围规则: ! '[48,110]'
  干扰带门限4:
    范围规则: ! '[48,110]'
  干扰带门限5:
    范围规则: ! '[48,110]'
  N200ofFACCH/全速率:
    范围规则: ! '[29,34]'
  N200ofFACCH/半速率:
    范围规则: ! '[29,34]'
  MS最大重发次数:
    范围规则: ! '{2_TIMES,4_TIMES,7_TIMES}'
ZPAR:
  最小接入电平:
    范围规则: ! '[7,25]'
  QSEARCH_I:
    范围规则: ! '[7,15]'
  TDD_OFFSET:
    范围规则: ! '[5,9]'
  下行功率控制:
    范围规则: ! '[0,1]'
  上行功率控制:
    范围规则: ! '[0,1]'
  BSS侧链路故障的计数器最大值:
    范围规则: ! '[7,15]'
  MS侧链路故障的计数器最大值:
    范围规则: ! '[7,15]'
  Bss侧检验无线链路故障的计数器S的最大值（AMRFR）:
    范围规则: ! '[7,15]'
  Bss侧检验无线链路故障的计数器S的最大值（AMRHR）:
    范围规则: ! '[7,15]'
GSMMR:
  上行话音质量Rxquality0: {}
  上行话音质量Rxquality1: {}
  上行话音质量Rxquality2: {}
  上行话音质量Rxquality3: {}
  上行话音质量Rxquality4: {}
  上行话音质量Rxquality5: {}
  上行话音质量Rxquality6: {}
  上行话音质量Rxquality7: {}
  上行质量总采样点:
    范围规则: ! '[0,1500000]'
    字段关联规则: ==上行话音质量Rxquality0+上行话音质量Rxquality1+上行话音质量Rxquality2+上行话音质量Rxquality3+上行话音质量Rxquality4+上行话音质量Rxquality5+上行话音质量Rxquality6+上行话音质量Rxquality7
  下行话音质量Rxquality0: {}
  下行话音质量Rxquality1: {}
  下行话音质量Rxquality2: {}
  下行话音质量Rxquality3: {}
  下行话音质量Rxquality4: {}
  下行话音质量Rxquality5: {}
  下行话音质量Rxquality6: {}
  下行话音质量Rxquality7: {}
  下行质量总采样点:
    范围规则: ! '[0,1500000]'
    字段关联规则: ==下行话音质量Rxquality0+下行话音质量Rxquality1+下行话音质量Rxquality2+下行话音质量Rxquality3+下行话音质量Rxquality4+下行话音质量Rxquality5+下行话音质量Rxquality6+下行话音质量Rxquality7
  DL电平值大于等于-85dBm的测量报告数:
    字段关联规则: <下行质量总采样点
  DL电平值大于等于-90dBm的测量报告数:
    字段关联规则: <下行质量总采样点
  DL电平值大于等于-94dBm的测量报告数:
    字段关联规则: <下行质量总采样点
